// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: msg.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace Msg
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Protocol
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"msgid")]
        public MessageID Msgid { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public LoginReq loginReq { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public LoginRsp loginRsp { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public KickNotify kickNotify { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public CreateRoomReq createRoomReq { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public CreateRoomRsp createRoomRsp { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public ConsumeDiamondsNotify consumeDiamondsNotify { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public JoinRoomReq joinRoomReq { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public JoinRoomRsp joinRoomRsp { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public JoinRoomNotify joinRoomNotify { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public LeaveRoomReq leaveRoomReq { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public LeaveRoomRsp leaveRoomRsp { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public LeaveRoomNotify leaveRoomNotify { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public SitDownReq sitDownReq { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public SitDownRsp sitDownRsp { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public SitDownNotify sitDownNotify { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        public StandUpReq standUpReq { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public StandUpRsp standUpRsp { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        public StandUpNotify standUpNotify { get; set; }

        [global::ProtoBuf.ProtoMember(23)]
        public AutoBankerReq autoBankerReq { get; set; }

        [global::ProtoBuf.ProtoMember(24)]
        public AutoBankerRsp autoBankerRsp { get; set; }

        [global::ProtoBuf.ProtoMember(25)]
        public StartGameReq startGameReq { get; set; }

        [global::ProtoBuf.ProtoMember(26)]
        public StartGameRsp startGameRsp { get; set; }

        [global::ProtoBuf.ProtoMember(27)]
        public BetReq betReq { get; set; }

        [global::ProtoBuf.ProtoMember(28)]
        public BetRsp betRsp { get; set; }

        [global::ProtoBuf.ProtoMember(29)]
        public BetNotify betNotify { get; set; }

        [global::ProtoBuf.ProtoMember(30)]
        public CombineReq combineReq { get; set; }

        [global::ProtoBuf.ProtoMember(31)]
        public CombineRsp combineRsp { get; set; }

        [global::ProtoBuf.ProtoMember(32)]
        public CombineNotify combineNotify { get; set; }

        [global::ProtoBuf.ProtoMember(34)]
        public GameStateNotify gameStateNotify { get; set; }

        [global::ProtoBuf.ProtoMember(35)]
        public DisconnectNotify disconnectNotify { get; set; }

        [global::ProtoBuf.ProtoMember(36)]
        public ReconnectNotify reconnectNotify { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginFBReq
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"fb_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string FbId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Token { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginReq
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public LoginType Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"fb")]
        public LoginFBReq Fb { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginRsp
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"ret")]
        public ErrorID Ret { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"uid")]
        public uint Uid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"room_id")]
        public uint RoomId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class KickNotify
    {
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DisconnectNotify
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"uid")]
        public uint Uid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReconnectNotify
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"uid")]
        public uint Uid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateRoomReq
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"min_bet")]
        public uint MinBet { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"max_bet")]
        public uint MaxBet { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"hands")]
        public uint Hands { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"credit_points")]
        public uint CreditPoints { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"is_share")]
        public bool IsShare { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateRoomRsp
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"ret")]
        public ErrorID Ret { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"room_id")]
        public uint RoomId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"room_number")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RoomNumber { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConsumeDiamondsNotify
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"diamonds")]
        public uint Diamonds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Player
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"uid")]
        public uint Uid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"seat_id")]
        public int SeatId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"bet")]
        public uint Bet { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Room
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"room_id")]
        public uint RoomId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"number")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Number { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"min_bet")]
        public uint MinBet { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"max_bet")]
        public uint MaxBet { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"hands")]
        public uint Hands { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"played_hands")]
        public uint PlayedHands { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"credit_points")]
        public uint CreditPoints { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"is_share")]
        public bool IsShare { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"players")]
        public global::System.Collections.Generic.List<Player> Players { get; } = new global::System.Collections.Generic.List<Player>();

        [global::ProtoBuf.ProtoMember(11, Name = @"state")]
        public GameState State { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"countdown")]
        public int Countdown { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"cards", IsPacked = true)]
        public uint[] Cards { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"result")]
        public global::System.Collections.Generic.List<SeatResult> Results { get; } = new global::System.Collections.Generic.List<SeatResult>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class JoinRoomReq
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"room_number")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RoomNumber { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class JoinRoomRsp
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"ret")]
        public ErrorID Ret { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"room")]
        public Room Room { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class JoinRoomNotify
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"uid")]
        public uint Uid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LeaveRoomReq
    {
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LeaveRoomRsp
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"ret")]
        public ErrorID Ret { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LeaveRoomNotify
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"uid")]
        public uint Uid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SitDownReq
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"seat_id")]
        public uint SeatId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SitDownRsp
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"ret")]
        public ErrorID Ret { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SitDownNotify
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public SitDownType Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"uid")]
        public uint Uid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"seat_id")]
        public uint SeatId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"old_seat_id")]
        public int OldSeatId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StandUpReq
    {
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StandUpRsp
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"ret")]
        public ErrorID Ret { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StandUpNotify
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"uid")]
        public uint Uid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"seat_id")]
        public uint SeatId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AutoBankerReq
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"auto_banker")]
        public bool AutoBanker { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AutoBankerRsp
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"ret")]
        public ErrorID Ret { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StartGameReq
    {
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StartGameRsp
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"ret")]
        public ErrorID Ret { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BetReq
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"chips")]
        public uint Chips { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BetRsp
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"ret")]
        public ErrorID Ret { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BetNotify
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"seat_id")]
        public uint SeatId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"chips")]
        public uint Chips { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CardGroup
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"cards", IsPacked = true)]
        public uint[] Cards { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CombineReq
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"card_groups")]
        public global::System.Collections.Generic.List<CardGroup> CardGroups { get; } = new global::System.Collections.Generic.List<CardGroup>();

        [global::ProtoBuf.ProtoMember(2, Name = @"autowin")]
        public bool Autowin { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CombineRsp
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"ret")]
        public ErrorID Ret { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CombineNotify
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"seat_id")]
        public uint SeatId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SeatResult
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"seat_id")]
        public uint SeatId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"card_groups")]
        public global::System.Collections.Generic.List<CardGroup> CardGroups { get; } = new global::System.Collections.Generic.List<CardGroup>();

        [global::ProtoBuf.ProtoMember(3, Name = @"autowin")]
        public bool Autowin { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"ranks", IsPacked = true)]
        public global::System.Collections.Generic.List<CardRank> Ranks { get; } = new global::System.Collections.Generic.List<CardRank>();

        [global::ProtoBuf.ProtoMember(5, Name = @"scores", IsPacked = true)]
        public int[] Scores { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"total_score")]
        public int TotalScore { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"win")]
        public int Win { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"bet")]
        public uint Bet { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameStateNotify
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"state")]
        public GameState State { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"countdown")]
        public uint Countdown { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"deal_cards", IsPacked = true)]
        public uint[] DealCards { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"result")]
        public global::System.Collections.Generic.List<SeatResult> Results { get; } = new global::System.Collections.Generic.List<SeatResult>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum MessageID
    {
        [global::ProtoBuf.ProtoEnum(Name = @"Login_Req")]
        LoginReq = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"Login_Rsp")]
        LoginRsp = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"Kick_Notify")]
        KickNotify = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"CreateRoom_Req")]
        CreateRoomReq = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"CreateRoom_Rsp")]
        CreateRoomRsp = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"ConsumeDiamonds_Notify")]
        ConsumeDiamondsNotify = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"JoinRoom_Req")]
        JoinRoomReq = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"JoinRoom_Rsp")]
        JoinRoomRsp = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"JoinRoom_Notify")]
        JoinRoomNotify = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"LeaveRoom_Req")]
        LeaveRoomReq = 9,
        [global::ProtoBuf.ProtoEnum(Name = @"LeaveRoom_Rsp")]
        LeaveRoomRsp = 10,
        [global::ProtoBuf.ProtoEnum(Name = @"LeaveRoom_Notify")]
        LeaveRoomNotify = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"SitDown_Req")]
        SitDownReq = 12,
        [global::ProtoBuf.ProtoEnum(Name = @"SitDown_Rsp")]
        SitDownRsp = 13,
        [global::ProtoBuf.ProtoEnum(Name = @"SitDown_Notify")]
        SitDownNotify = 14,
        [global::ProtoBuf.ProtoEnum(Name = @"StandUp_Req")]
        StandUpReq = 15,
        [global::ProtoBuf.ProtoEnum(Name = @"StandUp_Rsp")]
        StandUpRsp = 16,
        [global::ProtoBuf.ProtoEnum(Name = @"StandUp_Notify")]
        StandUpNotify = 17,
        [global::ProtoBuf.ProtoEnum(Name = @"AutoBanker_Req")]
        AutoBankerReq = 21,
        [global::ProtoBuf.ProtoEnum(Name = @"AutoBanker_Rsp")]
        AutoBankerRsp = 22,
        [global::ProtoBuf.ProtoEnum(Name = @"StartGame_Req")]
        StartGameReq = 23,
        [global::ProtoBuf.ProtoEnum(Name = @"StartGame_Rsp")]
        StartGameRsp = 24,
        [global::ProtoBuf.ProtoEnum(Name = @"Bet_Req")]
        BetReq = 25,
        [global::ProtoBuf.ProtoEnum(Name = @"Bet_Rsp")]
        BetRsp = 26,
        [global::ProtoBuf.ProtoEnum(Name = @"Bet_Notify")]
        BetNotify = 27,
        [global::ProtoBuf.ProtoEnum(Name = @"Combine_Req")]
        CombineReq = 28,
        [global::ProtoBuf.ProtoEnum(Name = @"Combine_Rsp")]
        CombineRsp = 29,
        [global::ProtoBuf.ProtoEnum(Name = @"Combine_Notify")]
        CombineNotify = 30,
        [global::ProtoBuf.ProtoEnum(Name = @"Result_Notify")]
        ResultNotify = 31,
        [global::ProtoBuf.ProtoEnum(Name = @"GameState_Notify")]
        GameStateNotify = 32,
        [global::ProtoBuf.ProtoEnum(Name = @"Disconnect_Notify")]
        DisconnectNotify = 33,
        [global::ProtoBuf.ProtoEnum(Name = @"Reconnect_Notify")]
        ReconnectNotify = 34,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ErrorID
    {
        Ok = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"Invalid_Params")]
        InvalidParams = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"DB_Error")]
        DBError = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"Internal_Error")]
        InternalError = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"CreateRoom_Invalid_Room_Name")]
        CreateRoomInvalidRoomName = 100,
        [global::ProtoBuf.ProtoEnum(Name = @"CreateRoom_Invalid_Min_Max_Bet")]
        CreateRoomInvalidMinMaxBet = 101,
        [global::ProtoBuf.ProtoEnum(Name = @"CreateRoom_Invalid_Credit_Points")]
        CreateRoomInvalidCreditPoints = 102,
        [global::ProtoBuf.ProtoEnum(Name = @"CreateRoom_Not_Enough_Diamonds")]
        CreateRoomNotEnoughDiamonds = 103,
        [global::ProtoBuf.ProtoEnum(Name = @"CreateRoom_Exceed_Limitation_Rooms")]
        CreateRoomExceedLimitationRooms = 104,
        [global::ProtoBuf.ProtoEnum(Name = @"CreateRoom_Invalid_Hands")]
        CreateRoomInvalidHands = 105,
        [global::ProtoBuf.ProtoEnum(Name = @"JoinRoom_Wrong_Room_Number")]
        JoinRoomWrongRoomNumber = 110,
        [global::ProtoBuf.ProtoEnum(Name = @"JoinRoom_Full")]
        JoinRoomFull = 111,
        [global::ProtoBuf.ProtoEnum(Name = @"JoinRoom_Already_In")]
        JoinRoomAlreadyIn = 112,
        [global::ProtoBuf.ProtoEnum(Name = @"LeaveRoom_Not_In")]
        LeaveRoomNotIn = 120,
        [global::ProtoBuf.ProtoEnum(Name = @"LeaveRoom_Playing")]
        LeaveRoomPlaying = 121,
        [global::ProtoBuf.ProtoEnum(Name = @"SitDown_Invalid_Seat_Id")]
        SitDownInvalidSeatId = 130,
        [global::ProtoBuf.ProtoEnum(Name = @"SitDown_Already_Exist_Player")]
        SitDownAlreadyExistPlayer = 131,
        [global::ProtoBuf.ProtoEnum(Name = @"SitDown_Already_Sit")]
        SitDownAlreadySit = 132,
        [global::ProtoBuf.ProtoEnum(Name = @"StandUp_Not_Sit")]
        StandUpNotSit = 140,
        [global::ProtoBuf.ProtoEnum(Name = @"StandUp_Cannot_Stand_Up")]
        StandUpCannotStandUp = 141,
        [global::ProtoBuf.ProtoEnum(Name = @"AutoBanker_Not_Banker")]
        AutoBankerNotBanker = 150,
        [global::ProtoBuf.ProtoEnum(Name = @"AutoBanker_Invalid_State")]
        AutoBankerInvalidState = 151,
        [global::ProtoBuf.ProtoEnum(Name = @"StartGame_Not_Banker")]
        StartGameNotBanker = 160,
        [global::ProtoBuf.ProtoEnum(Name = @"StartGame_Not_Enough_Players")]
        StartGameNotEnoughPlayers = 161,
        [global::ProtoBuf.ProtoEnum(Name = @"StartGame_Not_Enough_Diamonds")]
        StartGameNotEnoughDiamonds = 162,
        [global::ProtoBuf.ProtoEnum(Name = @"StartGame_Not_Ready_State")]
        StartGameNotReadyState = 163,
        [global::ProtoBuf.ProtoEnum(Name = @"Bet_Not_Bet_State")]
        BetNotBetState = 170,
        [global::ProtoBuf.ProtoEnum(Name = @"Bet_Banker_Cannot_Bet")]
        BetBankerCannotBet = 171,
        [global::ProtoBuf.ProtoEnum(Name = @"Bet_Invalid_Chips")]
        BetInvalidChips = 172,
        [global::ProtoBuf.ProtoEnum(Name = @"Bet_Not_A_Player_On_Seat")]
        BetNotAPlayerOnSeat = 173,
        [global::ProtoBuf.ProtoEnum(Name = @"Bet_Already_Bet")]
        BetAlreadyBet = 174,
        [global::ProtoBuf.ProtoEnum(Name = @"Combine_Not_Combine_State")]
        CombineNotCombineState = 180,
        [global::ProtoBuf.ProtoEnum(Name = @"Combine_Not_In_This_Round")]
        CombineNotInThisRound = 181,
        [global::ProtoBuf.ProtoEnum(Name = @"Combine_Invalid_Request_Data")]
        CombineInvalidRequestData = 182,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum LoginType
    {
        Facebook = 0,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum SitDownType
    {
        Sit = 0,
        Swap = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum GameState
    {
        Ready = 0,
        Bet = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"Confirm_Bet")]
        ConfirmBet = 2,
        Deal = 3,
        Combine = 4,
        Show = 5,
        Result = 6,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum CardRank
    {
        [global::ProtoBuf.ProtoEnum(Name = @"High_Card")]
        HighCard = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"One_Pair")]
        OnePair = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"Two_Pair")]
        TwoPair = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"Three_Of_A_Kind")]
        ThreeOfAKind = 3,
        Straight = 4,
        Flush = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"Full_House")]
        FullHouse = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"Four_Of_A_Kind")]
        FourOfAKind = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"Straight_Flush")]
        StraightFlush = 8,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum CardColorSuit
    {
        Clubs = 0,
        Spades = 1,
        Hearts = 2,
        Diamonds = 3,
        Count = 4,
    }

}

#pragma warning restore CS1591, CS0612, CS3021
